# Generated by Django 6.0.1 on 2026-01-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='price_per_night',
            new_name='price',
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
